src/Entity/Contact.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ApiResource()
 * @ORM\Entity(repositoryClass="App\Repository\ContactRepository")
 */
class Contact
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $movil;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phone_urgence;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $registre;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getMovil(): ?string
    {
        return $this->movil;
    }

    public function setMovil(?string $movil): self
    {
        $this->movil = $movil;

        return $this;
    }

    public function getPhoneUrgence(): ?string
    {
        return $this->phone_urgence;
    }

    public function setPhoneUrgence(?string $phone_urgence): self
    {
        $this->phone_urgence = $phone_urgence;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getRegistre(): ?string
    {
        return $this->registre;
    }

    public function setRegistre(?string $registre): self
    {
        $this->registre = $registre;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html lang="{{ app.request.locale }}">
<head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/x-icon" href="{{ asset('img/favicon.ico') }}" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {{ leogout_seo() }}
    {% block stylesheets %}

    {% endblock %}

    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-122199870-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-122199870-1');
  
</script>

</head>

<body id="{% block body_id %}{% endblock %}">

{% block header %}
    <header>
        <div class="navbar-fixed">
        <nav class="teal lighten-2" role="navigation">
            <div class="nav-wrapper">
                <a id="logo-container" href="/" class="brand-logo">
                    <img id="logo" src="{{ asset('img/Logo.png') }}" />
                </a>
                <div class="hide-on-med-and-up show-on-small container" style="width: min-content !important">
                    <div class="heading-container-small">
                    <a href="/">
                        <h4 class="m-0 heading-title-small"><span style="color: #565D96">arena</span>-<span style="color: #DC0024">park</span>.ch</h4>
                        <span class="m-0 heading-subtitle">voyagez l'esprit libre</span>
                    </a>
                    </div>
                </div>

                <div class="hide-on-small-only show-on-medium-and-up" style="display: inline-block">
                    <div class="heading-container">
                    <a href="/">
                        <h4 class="m-0 heading-title"><span style="color: #311b92">arena</span>-<span style="color: #DC0024">park</span>.ch</h4>
                        <span class="m-0 heading-subtitle">voyagez l'esprit libre</span>
                    </a>
                    </div>
                </div>
                <ul class="right hide-on-med-and-down menu-tab">
                    <li {% if home is defined %}class="active"{% endif %}><a href="/">Accueil</a></li>
                    <li {% if services is defined %}class="active"{% endif %}><a href="{{ path('service') }}">Services</a></li>
                    <li {% if tarif is defined %}class="active"{% endif %}><a href="{{ path('tarifs') }}">Tarifs</a></li>
                    <li {% if faq is defined %}class="active"{% endif %}><a href="{{ path('faq') }}">F.A.Q</a></li>
                    <li {% if contact is defined %}class="active"{% endif %}><a href="{{ path('contact') }}">Contact</a></li>
                    <li {% if reservation is defined %}class="active"{% endif %}><a href="{{ path('reservation') }}">Réservation</a></li>
                </ul>
                <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons" style="color: white !important;">menu</i></a>
            </div>

        </nav>
        </div>
    </header>
{% endblock %}

<main class="container">


    <ul id="nav-mobile" class="sidenav">
        <li {% if home is defined %}class="active"{% endif %}><a href="/">Accueil</a></li>
        <li {% if services is defined %}class="active"{% endif %}><a href="{{ path('service') }}">Services</a></li>
        <li {% if tarif is defined %}class="active"{% endif %}><a href="{{ path('tarifs') }}">Tarifs</a></li>
        <li {% if faq is defined %}class="active"{% endif %}><a href="{{ path('faq') }}">F.A.Q</a></li>
        <li {% if contact is defined %}class="active"{% endif %}><a href="{{ path('contact') }}">Contact</a></li>
        <li {% if reservation is defined %}class="active"{% endif %}><a href="{{ path('reservation') }}">Réservation</a></li>
    </ul>
    {% block body %}

    {% endblock %}
</main>

{% block footer %}
    <footer class="page-footer teal lighten-2">
        <div class="footer-copyright">
            <div class="container center-align">
                <h6>arena-park.ch | Copyright © 2014 | <a href="{{ path('conditions') }}" style="text-decoration: none; font-weight: bold; color: #004d40">Conditions Générales</a></h6>
            </div>
        </div>
    </footer>
{% endblock %}

{% block javascripts %}
    {{ encore_entry_script_tags('js/base') }}
{% endblock %}
    <script>
        (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id))
            return;
        js = d.createElement(s);
        js.id = id;
        js.src = "//connect.facebook.net/fr_FR/sdk.js#xfbml=1&version=v2.3&appId=347019838836163";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>
<script src="https://assurance.sysnetgs.com/assurancecard/be8e7fbc4499573fd49c094e465c61e68245f6bddb9f7a1d/cardJs" type="text/javascript"></script>
</body>
</html>

templates/contact.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('css/vuetify') }}
    {{ encore_entry_link_tags('css/contact') }}
{% endblock %}
{% block title %}{% endblock %}


{% block body %}
    <div class="section  no-pad-bot">
        <div class="row">
            <div class="col s12">
                <div class="card">
                    <div class="card-content">
                        <div class="row">
                            <div class="col s12">
                                {% for section in sections %}
                                    <p>
                                        {{ section.content | raw }}
                                    </p>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="row mt-5">
                            <div class="col s12 l6">
                                {% if contact.address %}
                                <p class="mb-1"><strong>Adresse:</strong> {{ contact.address }}</p>
                                {% endif %}
                                {% if contact.phone %}
                                    <p class="mb-1"><strong>Tél. Fixe:</strong> {{ contact.phone }}</p>
                                {% endif %}
                                {% if contact.movil %}
                                    <p class="mb-1"><strong>Tél. Voiturier:</strong> {{ contact.movil }}</p>
                                {% endif %}
                                {% if contact.phoneUrgence %}
                                    <p class="mb-1"><strong>Tél. Urgences:</strong> {{ contact.phoneUrgence }}</p>
                                {% endif %}
                                {% if contact.email %}
                                    <p class="mb-1"><strong>E-mail:</strong> {{ contact.email }}</p>
                                {% endif %}
                                {% if contact.registre %}
                                    <p><strong>Registre du commerce:</strong> {{ contact.registre }}</p>
                                {% endif %}
                            </div>
                            <div class="col s12 l6">
                                <div id="contact">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('js/contact') }}
{% endblock %}

templates/faq.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('css/faq') }}
{% endblock %}
{% block title %}{% endblock %}


{% block body %}
    <div class="section no-pad-bot">
        <div class="row">
            <div class="col s12">
                <ul class="collapsible">
                    {% for section in sections %}
                        <li>
                            <div class="collapsible-header">{{ section.title }}</div>
                            <div class="collapsible-body"><span>{{ section.content | raw }}</span></div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('js/faq') }}
{% endblock %}

templates/general-condition.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('css/tarif') }}
{% endblock %}
{% block title %}{% endblock %}

{% block body %}
    <div class="section  no-pad-bot">
        <div class="row">
            <div class="col s12">
                <div class="card">
                    <div class="card-content">
                        {% for section in sections %}
                            <div class="mt-5"></div>
                            {% if section.title is not empty %}
                                <span class="card-title">{{ section.title }}</span><br>
                            {% endif %}
                            <p>
                                {{ section.content | raw }}
                            </p>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/pdf-resumen.html.twig
<div style="margin-bottom: 30px; text-align: center">
    <img src="https://arena-park.ch/img/Logo.png" style="max-height: 100px">
</div>
<p style="font-size: 12px; position: fixed; right: 0px">www.arena-park.ch</p>
<h3 style="margin-bottom: 30px"><strong>{{ date }} Départ et arrivée des voitures</strong></h3>

<h4 style="margin-bottom: 10px">Depart: {{ reservations.carIn | length  }}</h4>
{% if reservations.carIn is not empty %}
<table style="width: 100%">
    <thead>
     <tr>
        <td><strong>Nom</strong></td>
        <td><strong>Téléphone</strong></td>
        <td><strong>Décollage</strong></td>
         <td><strong>Vol</strong></td>
         <td><strong>Prise en charge</strong></td>
        <td><strong>Plate</strong></td>
        <td><strong>Marque</strong></td>
     </tr>
    </thead>
    {% for key, data in reservations.carIn %}
     <tr>
        <td>{{ key + 1 }}.-{{ data.user.name }}</td>
         <td>{{ data.user.phone }}</td>
        <td>{{ data.dateFlyOut | date('m/d/Y H:i') }}</td>
        <td>{{ data.fly }}</td>
         <td>{{ data.dateCarIn | date('m/d/Y H:i') }}</td>
        <td>{{ data.car.plate }}</td>
        <td>{{ data.car.mark }}</td>
     </tr>
    {% endfor %}
</table>
    </br></br></br>
{% endif %}
 
<h4 style="margin-bottom: 10px">Arrivée: {{ reservations.carOut | length  }}</h4>
{% if reservations.carOut is not empty %}

    <table style="width: 100%">
        <thead>
        <tr>
            <td><strong>Nom</strong></td>
            <td><strong>Téléphone</strong></td>
            <td><strong>Arrivée</strong></td>
            <td><strong>Vol</strong></td>
            <td><strong>Restitution</strong></td>
            <td><strong>Plate</strong></td>
            <td><strong>Marque</strong></td>
        </tr>
        </thead>
        {% for key, data in reservations.carOut %}
            <tr>
                <td>{{ key + 1 }}.-{{ data.user.name }}</td>
                <td>{{ data.user.phone }}</td>
                <td>{{ data.dateFlyIn | date('m/d/Y H:i') }}</td>
                <td>{{ data.fly }}</td>
                <td>{{ data.dateCarOut | date('m/d/Y H:i') }}</td>
                <td>{{ data.car.plate }}</td>
                <td>{{ data.car.mark }}</td>
            </tr>
        {% endfor %}
    </table>
{% endif %}

templates/reservation.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('css/vuetify') }}
    {{ encore_entry_link_tags('css/reservation') }}
{% endblock %}
{% block title %}{% endblock %}


{% block body %}
    <div id="reservation">
    </div>
{% endblock %}
{% block javascripts %}
    <script>
                {% if errorPayment is defined %}var errorPayment = '{{ errorPayment }}'{% endif %}
                {% if reservationConfirmed is defined %}var reservationConfirmed = true{% endif %}
                var id = '{{id}}'
    </script>
    {{ parent() }}
    {{ encore_entry_script_tags('js/reservation') }}
{% endblock %}

templates/services.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('css/services') }}
{% endblock %}
{% block title %}{% endblock %}


{% block body %}
    <div class="section  no-pad-bot hide-on-small-only show-on-medium-and-up">
        <div class="row">
            <div class="col s12">
                <div class="card">
                    <div class="card-content">
                        {% if eachCar | length %}
                            <table class="responsive-table">
                                <thead>
                                <tr>
                                    <th></th>
                                    <th><i class="small material-icons small_car">local_car_wash</i></th>
                                    <th><i class="small material-icons middle_car">local_car_wash</i></th>
                                    <th><i class="small material-icons big_car">local_car_wash</i></th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for service in eachCar %}
                                    <tr>
                                        <td>{{ service.name }}</td>
                                        <td>{{ service.small }} CHF</td>
                                        <td>{{ service.middle }} CHF</td>
                                        <td>{{ service.big }} CHF</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        {% endif %}
                        <div class="my-3"></div>
                        {% if allCar | length %}
                            <table class="responsive-table centered">
                                <thead>
                                <tr>
                                    <th></th>
                                    <th>
                                        <i class="small material-icons small_car" color="teal">local_car_wash</i>
                                        <i class="small material-icons middle_car">local_car_wash</i>
                                        <i class="small material-icons big_car">local_car_wash</i>
                                    </th>
                                    <th></th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for service in allCar %}
                                    <tr>
                                        <td class="left">{{ service.name }}</td>
                                        <td>{{ service.all }} CHF</td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        {% endif %}
                        <div class="my-3"></div>
                        <p>
                            {{ sections['section1'].content | raw }}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="section  no-pad-bot hide-on-med-and-up show-on-small">
        {% if eachCar | length %}
            <div class="row">
                <div class="col s6"></div>
                <div class="col s2 p-0"><i class="small material-icons small_car">local_car_wash</i></div>
                <div class="col s2 p-0"><i class="small material-icons middle_car">local_car_wash</i></div>
                <div class="col s2 p-0"><i class="small material-icons big_car">local_car_wash</i></div>
            </div>
            {% for service in eachCar %}
                <div class="row">
                    <div class="col s6">{{ service.name }}</div>
                    <div class="col s2 p-0">{{ service.small }} CHF</div>
                    <div class="col s2 p-0">{{ service.middle }} CHF</div>
                    <div class="col s2 p-0">{{ service.big }} CHF</div>
                </div>
            {% endfor %}
        {% endif %}
        <div class="my-3"></div>
        {% if allCar | length %}
            <div class="row">
                <div class="col s6"></div>
                <div class="col s4 center">
                    <i class="small material-icons small_car" color="teal">local_car_wash</i>
                    <i class="small material-icons middle_car">local_car_wash</i>
                    <i class="small material-icons big_car">local_car_wash</i>
                </div>
            </div>
            {% for service in allCar %}
                <div class="row">
                    <div class="col s6">{{ service.name }}</div>
                    <div class="col s4 center">{{ service.all }} CHF</div>
                </div>
            {% endfor %}
        {% endif %}
        <div class="my-3"></div>
        <div class="row">
            <div class="col s12">
                <p>
                    {{ sections['section1'].content | raw }}
                </p>
            </div>
        </div>
    </div>

{% endblock %}

templates/tarif.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('css/tarif') }}
{% endblock %}
{% block title %}{% endblock %}


{% block body %}
    <div class="section  no-pad-bot">
        <div class="row">
            <div class="col s12">
                <div class="card">
                    <div class="card-content">
                            <table class="responsive-table">
                                <tbody>
                                    <tr>
                                        <td>Jours</td>
                                        <td>{{ tarifs.day }} CHF</td>
                                    </tr>
                                    <tr>
                                        <td>Prise en charge du véhicule (obligatoire)</td>
                                        <td>{{ tarifs.priceCharge }} CHF</td>
                                    </tr>
                                    <tr>
                                        <td>Assurance annulation vol (obligatoire)</td>
                                        <td>{{ tarifs.annulation }} CHF</td>
                                    </tr>
                                </tbody>
                            </table>
                        <div class="my-3"></div>
                        {% for section in sections %}
                            <p>
                                {{ section.content | raw }}
                            </p>
                        {% endfor %}

                    </div>
                </div>

                {% if discounts is not empty %}
                    <div class="card">
                    <div class="card-content">
                            <table class="responsive-table">
                                <tbody>
                                    <tr>
                                        <td>Réservations sur 12 mois</td>
                                        <td>Taux de récompense</td>
                                    </tr>
                                    {% for discount in discounts %}
                                      <tr >
                                        <td>{{discount.min }}{{discount.max ? '-'~ discount.max : '+'}}</td>
                                        <td>{{ discount.discount }}%</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                    </div>
                    </div>
                    {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/unsubscribe.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('css/contact') }}
{% endblock %}
{% block title %}{% endblock %}


{% block body %}
    <div class="section no-pad-bot">
        <div class="row">
            <div class="col s12">
            <div class="card">
             <div class="card-content">
                <div style="font-size: 22px; text-align: center;">
                 Vous avez réussi à vous désinscrire
                </div>
             </div>
            </div>
            </div>
        </div>
    </div>
{% endblock %}